name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number.'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker pull null511/pixelgraph
      - name: Publish Bare-Bones-PBR-128x
        run: |
          docker run --name pixelgraph --rm --mount src="$(pwd)",target=/content,type=bind null511/pixelgraph \
            publish -p "//content/src/lab13-128x.pack.yml" -z "//content/Bare-Bones-PBR-128x.zip"
      - name: Publish Bare-Bones-PBR-32x
        run: |
          docker run --name pixelgraph --rm --mount src="$(pwd)",target=/content,type=bind null511/pixelgraph \
            publish -p "//content/src/lab13-32x.pack.yml" -z "//content/Bare-Bones-PBR-32x.zip"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
      - name: Upload Bare-Bones-PBR-128x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Bare-Bones-PBR-128x.zip
          asset_name: Bare-Bones-PBR-128x.zip
          asset_content_type: application/zip
      - name: Upload Bare-Bones-PBR-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Bare-Bones-PBR-32x.zip
          asset_name: Bare-Bones-PBR-32x.zip
          asset_content_type: application/zip
